apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: 'true'
  name: hello-world
  labels:
    name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
        - name: hello-world
          image: gcr.io/weave-flux-trial/weave-flux-trial:master-45680f3
          ports:
            - containerPort: 8080
